core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('netkineskop.urls', namespace='netkineskop')),
]

netkineskop/urls.py
from django.urls import path, re_path

from . import views



app_name = 'netkineskop'

urlpatterns = [
    re_path(r'^$|home/', views.home, name='home'),
    path('tags/', views.TagView.as_view(), name='tags'),
    path('tags/<int:pk>', views.DetailTagView.as_view(), name='detail_tag'),
    path('tags/<int:pk>/delete/', views.DeleteTagView.as_view(), name='delete_tag'),
    path('tags/<int:pk>/edit/', views.UpdateTagView.as_view(), name='update_tag'),
    path('add_tag/', views.AddTagView.as_view(), name='add_tag'),
    path('subscriptions/', views.subscriptions, name='subscriptions'),
    path('videos/', views.videos, name='videos'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous"/>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    <title>NetKineskop</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-danger">
      <div class="container-sm justify-content-between">
        <a class="navbar-brand" href="{% url 'netkineskop:home' %}">
          <strong>
            <span class="text-white">Net</span><span class="text-dark">Kineskop</span>
          </strong>
        </a>
        <span>
          <a class="btn btn-outline-primary" href="{% url 'netkineskop:tags' %}">
            Tags
          </a>
          <a class="btn btn-outline-warning" href="{% url 'netkineskop:subscriptions' %}">
            Subscriptions
          </a>
          <a class="btn btn-outline-light" href="{% url 'netkineskop:videos' %}">
            Videos
          </a>
        </span>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">
            Profile
          </button>
          <ul class="dropdown-menu dropdown-menu-md-right">
            {% if request.user.is_authenticated %}
            <li>
              <a class="dropdown-item form-control text-secondary" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
            <li>
              <a class="dropdown-item form-control text-secondary" href="{% url 'login' %}">Sign In</a>
            </li>
            <li>
              <a class="dropdown-item form-control text-secondary" href="{% url 'register' %}">Sign Up</a>
            </li>
            {% endif %}
            {% if 'credentials' in request.session %}
            <li>
              <form class="dropdown-item" action="{% url 'oauth_authorize' %}" method="get">
                <input class="form-control" type="submit" value="Connect YouTube"/>
              </form>
            </li>
            {% else %}
            <li>
              <a class="dropdown-item form-control text-secondary" href="{% url 'oauth_revoke' %}">
                Disconnect YouTube
              </a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-sm my-4">
      {% block content %}{% endblock content %}
    </div>
    <script>
    {% block javascript %}
    {% endblock javascript %}
    </script>
  </body>
</html>