core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('netkineskop.urls', namespace='netkineskop')),
]

netkineskop/urls.py
from django.urls import path, re_path

from . import views



app_name = 'netkineskop'

urlpatterns = [
    re_path(r'^$|home/', views.home, name='home'),
    path('tags/', views.TagView.as_view(), name='tags'),
    path('tags/<int:pk>', views.DetailTagView.as_view(), name='detail_tag'),
    path('tags/<int:pk>/delete/', views.DeleteTagView.as_view(), name='delete_tag'),
    path('tags/<int:pk>/edit/', views.UpdateTagView.as_view(), name='update_tag'),
    path('add_tag/', views.AddTagView.as_view(), name='add_tag'),
    path('subscriptions/', views.subscriptions, name='subscriptions'),
    path('videos/', views.videos, name='videos'),
]

netkineskop/models.py
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models



class Tag(models.Model):
    user = models.ForeignKey(
        User, related_name='tags', blank=False, on_delete=models.CASCADE
    )
    name = models.CharField(max_length=32)
    color = models.CharField(
        max_length=7,
        blank=True,
        default='#cccccc',
        validators=[RegexValidator(r'^#[0-9a-fA-F]{6}$')]
    )

    def __str__(self):
        return f'{self.name}'


class Channel(models.Model):
    user = models.ForeignKey(
        User, related_name='channels', blank=False, on_delete=models.CASCADE
    )
    yt_channel_id = models.CharField(max_length=64)
    name = models.CharField(max_length=128, blank=True, default='<name placeholder>')

    tags = models.ManyToManyField(Tag, related_name='channels', through='ChannelTag')

    def __str__(self):
        return f'{self.name}'


class ChannelTag(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE)
    favorite = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.tag} : {self.channel}'

    class Meta:
        unique_together = ('tag', 'channel')

netkineskop/forms.py
from django import forms

from .models import Tag



class TagForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = ('name', 'color')
        widgets = {
            'color': forms.widgets.TextInput(attrs={
                'type': 'color'
            })
        }

netkineskop/views.py
import google.oauth2.credentials
import googleapiclient.discovery

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from . import yt_services
from .models import Tag, Channel, ChannelTag
from .forms import TagForm
from .permissions import TagUserPermission
from accounts.views import credentials_to_dict



def home(request):
    return render(request, 'netkineskop/home.html')


class TagView(LoginRequiredMixin, ListView):
    model = Tag
    template_name = 'netkineskop/user_tags.html'
    context_object_name = 'user_tags'
    paginate_by = 15

    def get_queryset(self):
        current_user = self.request.user
        return current_user.tags.all()


class AddTagView(LoginRequiredMixin, CreateView):
    model = Tag
    form_class = TagForm
    template_name = 'netkineskop/add_tag.html'
    success_url = '/tags/'

    def form_valid(self, form):
        form.instance.user_id = self.request.user.id
        return super().form_valid(form)


class DeleteTagView(TagUserPermission, DeleteView):
    model = Tag
    success_url = '/tags/'


class UpdateTagView(TagUserPermission, UpdateView):
    model = Tag
    form_class = TagForm
    template_name = 'netkineskop/edit_tag.html'
    success_url = '/tags/'


class DetailTagView(TagUserPermission, DetailView):
    model = Tag
    template_name ='netkineskop/detail_tag.html'


def subscriptions(request):
    if 'credentials' not in request.session:
        return redirect('oauth_authorize')

    credentials = google.oauth2.credentials.Credentials(**request.session['credentials'])
    youtube = googleapiclient.discovery.build(
        settings.API_SERVICE_NAME, settings.API_VERSION, credentials=credentials
    )
    request.session['credentials'] = credentials_to_dict(credentials)

    subscribed_channels = yt_services.get_subscriptions(youtube)

    context = dict(subscriptions=subscribed_channels)
    return render(request, 'netkineskop/subscriptions.html', context)


def videos(request):
    if 'credentials' not in request.session:
        return redirect('oauth_authorize')

    credentials = google.oauth2.credentials.Credentials(**request.session['credentials'])
    youtube = googleapiclient.discovery.build(
        settings.API_SERVICE_NAME, settings.API_VERSION, credentials=credentials
    )
    response = youtube.subscriptions().list(part='snippet', mine='true')
    request.session['credentials'] = credentials_to_dict(credentials)
    subscribed_videos = response.execute()
    imgs = [
        v for k, v in subscribed_videos.items()
    ]
    channel_ids = [
        img['snippet']['resourceId']['channelId']
        for img in imgs[4]
    ]

    response_videos = youtube.channels().list(
        part='contentDetails',
        id=','.join(id for id in channel_ids)
    )
    videos = response_videos.execute()
    channels = [{
        'id': video['id'],
        'uploads': video['contentDetails']['relatedPlaylists']['uploads']
        }
        for video in videos['items']
    ]
    from pprint import pprint
    # print(f'Channels ######## : {channels}')
    uploads = list()
    for channel in channels:
        response_vids = youtube.playlistItems().list(
            part='snippet, contentDetails',
            playlistId=channel['uploads'],
            maxResults=50,
            pageToken=None
        )
        uploads.append(response_vids.execute())

    videos_all = list()
    for vids in uploads:
        for vid in vids['items']:
            videos_all.append({
                'channel_id': vid['snippet']['channelId'],
                'channel_title': vid['snippet']['channelTitle'],
                'published_at': vid['snippet']['publishedAt'],
                'thumbnail_url': vid['snippet']['thumbnails']['medium']['url'],
                'video_title': vid['snippet']['title'],
                'video_url': vid['snippet']['resourceId']['videoId']
        })
    # pprint(videos_all)
    context = dict(imgs=imgs, videos=videos_all)
    return render(request, 'netkineskop/videos.html', context)

templates/netkineskop/add_tag.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
<form class="row g-3" action="{% url 'netkineskop:add_tag' %}" method="post">
  {% csrf_token %}
  <div class="col-1 d-flex justify-content-center align-items-center">
    <input class="bg-transparent" name="color" type="color" value="" title="Choose color for Tag"/>
  </div>
  <div class="col-8">
    <input class="form-control bg-transparent text-light" name="name" type="text" placeholder="name"/>
  </div>
  <div class="col-3">
    <input class="form-control btn-outline-success bg-transparent" type="submit" value="Add Tag"/>
  </div>
</form>
{% endblock content %}

{% block javascript %}
document.addEventListener('DOMContentLoaded', () => {
  var randomColor = Math.floor(Math.random()*16777215).toString(16)
  document.querySelector('input[name="color"]').value = `#${randomColor}`
})
{% endblock %}

templates/netkineskop/detail_tag.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex align-items-center border border-success rounded p-3">
  <span>
    <h3 class="m-0 text-success">TAG Overview</h3>
  </span>
</div>
<div class="list-group mt-4 px-3">
    <span class="list-group-item list-group-item-action d-inline-flex bg-dark text-light text-truncate"
        href="{{ tag.id }}">
      <span>
          <div class="d-inline-block align-middle rounded-sm rounded-circle" style="background: {{tag.color}}; width: 10px; height: 10px;"></div>
          <span class="ml-1">{{ tag.name }}</span>
      </span>
      {% if tag.channels.all %}
      <ul class="list-group">
        {% for channel in tag.channels.all %}
        <li class="list-group-item list-group-item-action">{{ channel.yt_channel_id }}</li>
        {% endfor %}
      </ul>
      {% endif %}
    </span>
</div>
{% endblock content %}

templates/netkineskop/edit_tag.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block content %}
<form class="row g-3" action="" method="post">
  {% csrf_token %}
  <div class="col-1 d-flex justify-content-center align-items-center">
    <input class="bg-transparent" name="color" type="color" value="{{ form.color.value }}"
        title="Choose color for Tag"/>
  </div>
  <div class="col-8">
    <input class="form-control bg-transparent text-light" name="name" type="text"
        placeholder="name" value="{{ form.name.value }}"/>
  </div>
  <div class="col-3">
    <input class="form-control btn-outline-success bg-transparent" type="submit" value="Apply"/>
  </div>
</form>
{% endblock content %}

templates/netkineskop/home.html
{% extends 'base.html' %}

{% block content %}
<h1 class="text-white-50">Home page!</h1>
<h6 class="text-white-50">Sign In to enjoy full functionality</h6>
{% endblock content %}

templates/netkineskop/paginator.html
<div class="col-12 mt-5 text-white-50">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>

templates/netkineskop/subscriptions.html
{% extends 'base.html' %}

{% block content %}
<button type="button" class="btn btn-dark my-4">
  Total Subscriptions <span class="badge bg-success">{{ subscriptions.total }}</span>
</button>
<span>
  <i class="fa fa-star-o text-warning"></i>
</span>
<div class="row g-2 my-4">
  {% for item in subscriptions.channels %}
  <div class="col-sm-6 col-md-4 col-lg-3 col-xxl-2">
    <div class="card card-hover rounded bg-dark text-white-50">
      <div class="row g-1">
        <div class="col-4 p-2">
          <img class="rounded-circle" src="{{ item.thumbnail }}" alt="channel_image"
              width="50px" height="50px"/>
        </div>
        <div class="col-8">
          <div class="card-body p-1"></div>
        </div>
      </div>
      <div class="card-footer d-flex justify-content-between">
        <small class="d-block text-truncate">{{ item.title }}</small>
        <i class="tag_menu fa fa-map-pin text-light" id="{{ item.channel_id }}"></i>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% include './tag_modal.html' %}
{% endblock content %}

{% block javascript %}
var tag_modal = new bootstrap.Modal(document.getElementById('tag-menu'))
var tags_menu = document.querySelectorAll('.tag_menu')

tags_menu.forEach(tag_menu => {
  tag_menu.addEventListener('click', () => {
    var channel_name = tag_menu.previousElementSibling.textContent
    var channel_image = tag_menu.parentElement.parentElement.querySelector('img').src
    document.querySelector('#channel-name').textContent = `${channel_name}`
    document.querySelector('#channel-image').src = channel_image
    document.querySelector('#channel-id').value = tag_menu.id
    tag_modal.show()
  })
})
{% endblock javascript %}

templates/netkineskop/tag_modal.html
<div class="modal fade" id="tag-menu" tabindex="-1" aria-labelledby="TagMenu" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="tag-menu-label">Choose Tag</h5>
        <img class="rounded-circle" src="" alt="channel_image" id="channel-image"
              width="50px" height="50px"/>
      </div>
      <div class="modal-body">
        <form action="{% url 'netkineskop:mark_channel' %}" method="post" id="tag-form">
          {% csrf_token %}
          <div class="mb-3">
            <span class="" id="channel-name"></span>
          </div>
          <input type="hidden" name="channel_id" value="" id="channel-id"/>
          <div class="mb-3">
            <select class="form-select" name="tag_id" id="select-tag" required>
              <option disabled selected value>-- Choose one of your tags --</option>
              {% for tag in request.user.tags.all %}
              <option value="{{ tag.id }}">{{ tag.name }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="form-check">
            <input class="form-check-input" name="favorite" type="checkbox" value="" id="is-favorite">
            <label class="form-check-label" for="is_favorite">
              Favorite
            </label>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="submit-button">Apply</button>
      </div>
    </div>
  </div>
</div>
<script>
const tag_form = document.querySelector('#tag-form')

document.querySelector('#submit-button').addEventListener('click', () => {
  var chosen_tag = document.getElementById('select-tag').value
  if(chosen_tag != '') {
    tag_form.submit()
  }
})
</script>

templates/netkineskop/user_tags.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-between align-items-center border border-success rounded py-2 px-3">
  <span>
    <h3 class="m-0 text-success">TAG Center</h3>
  </span>
  <span class="d-flex justify-content-end">
    <a href="{% url 'netkineskop:add_tag'%}">
      <i class="fa fa-plus fa-3x text-light" title="Create new TAG"></i>
    </a>
  </span>
</div>
<div class="list-group mt-4 px-3">
  {% for tag in user_tags %}
    <button class="list-group-item list-group-item-action d-inline-flex align-items-center bg-dark text-light text-truncate"
        id="{{ tag.id }}">
      <span class="d-flex align-items-center">
        <div class="d-inline-block align-middle rounded-sm rounded-circle" style="background: {{ tag.color }}; width: 10px; height: 10px;"></div>
        <span class="ml-1">{{ tag.name }}</span>
      </span>
      <span class="d-flex justify-content-between align-items-center ml-auto">
        <span class="badge rounded-pill mr-3 bg-light text-dark">
          {{ tag.channels.all|length }}
        </span>
        <a class="btn btn-sm btn-info mr-2 py-0" href="{% url 'netkineskop:update_tag' tag.id %}">Edit</a>
        <form class="" action="{% url 'netkineskop:delete_tag' tag.id %}" method="post">
          {% csrf_token %}
          <input type="submit" class="fa fa-times fa-2x border-0 p-0 bg-transparent text-danger" value="&#xf057"/>
        </form>
      </span>
    </button>
  {% endfor %}
</div>
{% include 'netkineskop/paginator.html' %}
{% endblock content %}

{% block javascript %}
var items_detail = document.querySelectorAll('button.list-group-item')
var href = window.location.href

items_detail.forEach(item => {
  item.addEventListener('click', () => {
    window.location.href += item.id
  })
})
{% endblock javascript%}

templates/netkineskop/videos.html
{% extends 'base.html' %}

{% block content %}
<div class="input-group my-5 shadow-sm sticky-top">
  <span class="input-group-text" id="basic-addon1">Subscriptions</span>
  <input class="form-control" type="text" name="yt_video" placeholder="Search title"/>
</div>
{% for img in imgs.4 %}
<div class="">
  <span>{{img.snippet.title}}</span>
  <a href="https://www.youtube.com/channel/{{img.snippet.resourceId.channelId}}">Kanał</a>
</div>
{% endfor %}

<div class="row g-2">
  {% for item in videos %}
  <div class="col-sm-6 col-md-4 col-lg-3 col-xxl-2">
    <div class="card card-hover h-100 rounded bg-dark text-white-50">
      <iframe class="card-img-top" src="https://www.youtube.com/watch?v=5AOn0BmSXyE" title="W3Schools Free Online Web Tutorials"></iframe>
      <!-- <img class="card-img-top" src="{{item.thumbnail_url}}"/> -->
      <div class="card-body">
        <h5 class="card-title">{{item.channel_title}}</h5>
        <p class="card-text">
          {{item.video_title}}
        </p>
      </div>
      <div class="card-footer">
        <small class="text-muted">
          {{item.published_at|date:'Y-m-d G:i'}}
        </small>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}